name: SnowHalation
main: ifteam\SnowHalation\SnowHalation
version: 1.7-alpha
author: ifteam
api: [1.12.0]

commands:
 snow:
   permission: snowhalation
   description: SnowHalation control commands
   usage: /snow

permissions:
 snowhalation:
  default: true
  description: Allows commands of SnowHalation